// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/grpc/allidb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlliDBClient is the client API for AlliDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlliDBClient interface {
	// PutEntity stores a single entity
	PutEntity(ctx context.Context, in *PutEntityRequest, opts ...grpc.CallOption) (*PutEntityResponse, error)
	// BatchPutEntities stores multiple entities in a single request
	BatchPutEntities(ctx context.Context, in *BatchPutEntitiesRequest, opts ...grpc.CallOption) (*BatchPutEntitiesResponse, error)
	// Query performs a vector + graph search query
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// RangeScan scans entities by key range (inclusive start, exclusive end)
	RangeScan(ctx context.Context, in *RangeScanRequest, opts ...grpc.CallOption) (*RangeScanResponse, error)
	// ReplicaRead reads a raw value by key (for internal replication)
	ReplicaRead(ctx context.Context, in *ReplicaReadRequest, opts ...grpc.CallOption) (*ReplicaReadResponse, error)
	// ReplicaWrite writes a raw value by key (for internal replication)
	ReplicaWrite(ctx context.Context, in *ReplicaWriteRequest, opts ...grpc.CallOption) (*ReplicaWriteResponse, error)
	// HealthCheck checks the health of the service
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type alliDBClient struct {
	cc grpc.ClientConnInterface
}

func NewAlliDBClient(cc grpc.ClientConnInterface) AlliDBClient {
	return &alliDBClient{cc}
}

func (c *alliDBClient) PutEntity(ctx context.Context, in *PutEntityRequest, opts ...grpc.CallOption) (*PutEntityResponse, error) {
	out := new(PutEntityResponse)
	err := c.cc.Invoke(ctx, "/allidb.AlliDB/PutEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alliDBClient) BatchPutEntities(ctx context.Context, in *BatchPutEntitiesRequest, opts ...grpc.CallOption) (*BatchPutEntitiesResponse, error) {
	out := new(BatchPutEntitiesResponse)
	err := c.cc.Invoke(ctx, "/allidb.AlliDB/BatchPutEntities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alliDBClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/allidb.AlliDB/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alliDBClient) RangeScan(ctx context.Context, in *RangeScanRequest, opts ...grpc.CallOption) (*RangeScanResponse, error) {
	out := new(RangeScanResponse)
	err := c.cc.Invoke(ctx, "/allidb.AlliDB/RangeScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alliDBClient) ReplicaRead(ctx context.Context, in *ReplicaReadRequest, opts ...grpc.CallOption) (*ReplicaReadResponse, error) {
	out := new(ReplicaReadResponse)
	err := c.cc.Invoke(ctx, "/allidb.AlliDB/ReplicaRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alliDBClient) ReplicaWrite(ctx context.Context, in *ReplicaWriteRequest, opts ...grpc.CallOption) (*ReplicaWriteResponse, error) {
	out := new(ReplicaWriteResponse)
	err := c.cc.Invoke(ctx, "/allidb.AlliDB/ReplicaWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alliDBClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/allidb.AlliDB/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlliDBServer is the server API for AlliDB service.
// All implementations must embed UnimplementedAlliDBServer
// for forward compatibility
type AlliDBServer interface {
	// PutEntity stores a single entity
	PutEntity(context.Context, *PutEntityRequest) (*PutEntityResponse, error)
	// BatchPutEntities stores multiple entities in a single request
	BatchPutEntities(context.Context, *BatchPutEntitiesRequest) (*BatchPutEntitiesResponse, error)
	// Query performs a vector + graph search query
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// RangeScan scans entities by key range (inclusive start, exclusive end)
	RangeScan(context.Context, *RangeScanRequest) (*RangeScanResponse, error)
	// ReplicaRead reads a raw value by key (for internal replication)
	ReplicaRead(context.Context, *ReplicaReadRequest) (*ReplicaReadResponse, error)
	// ReplicaWrite writes a raw value by key (for internal replication)
	ReplicaWrite(context.Context, *ReplicaWriteRequest) (*ReplicaWriteResponse, error)
	// HealthCheck checks the health of the service
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAlliDBServer()
}

// UnimplementedAlliDBServer must be embedded to have forward compatible implementations.
type UnimplementedAlliDBServer struct {
}

func (UnimplementedAlliDBServer) PutEntity(context.Context, *PutEntityRequest) (*PutEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutEntity not implemented")
}
func (UnimplementedAlliDBServer) BatchPutEntities(context.Context, *BatchPutEntitiesRequest) (*BatchPutEntitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchPutEntities not implemented")
}
func (UnimplementedAlliDBServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAlliDBServer) RangeScan(context.Context, *RangeScanRequest) (*RangeScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RangeScan not implemented")
}
func (UnimplementedAlliDBServer) ReplicaRead(context.Context, *ReplicaReadRequest) (*ReplicaReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaRead not implemented")
}
func (UnimplementedAlliDBServer) ReplicaWrite(context.Context, *ReplicaWriteRequest) (*ReplicaWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaWrite not implemented")
}
func (UnimplementedAlliDBServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAlliDBServer) mustEmbedUnimplementedAlliDBServer() {}

// UnsafeAlliDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlliDBServer will
// result in compilation errors.
type UnsafeAlliDBServer interface {
	mustEmbedUnimplementedAlliDBServer()
}

func RegisterAlliDBServer(s grpc.ServiceRegistrar, srv AlliDBServer) {
	s.RegisterService(&AlliDB_ServiceDesc, srv)
}

func _AlliDB_PutEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlliDBServer).PutEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allidb.AlliDB/PutEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlliDBServer).PutEntity(ctx, req.(*PutEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlliDB_BatchPutEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPutEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlliDBServer).BatchPutEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allidb.AlliDB/BatchPutEntities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlliDBServer).BatchPutEntities(ctx, req.(*BatchPutEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlliDB_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlliDBServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allidb.AlliDB/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlliDBServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlliDB_RangeScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlliDBServer).RangeScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allidb.AlliDB/RangeScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlliDBServer).RangeScan(ctx, req.(*RangeScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlliDB_ReplicaRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlliDBServer).ReplicaRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allidb.AlliDB/ReplicaRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlliDBServer).ReplicaRead(ctx, req.(*ReplicaReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlliDB_ReplicaWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlliDBServer).ReplicaWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allidb.AlliDB/ReplicaWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlliDBServer).ReplicaWrite(ctx, req.(*ReplicaWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlliDB_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlliDBServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/allidb.AlliDB/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlliDBServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlliDB_ServiceDesc is the grpc.ServiceDesc for AlliDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlliDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "allidb.AlliDB",
	HandlerType: (*AlliDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEntity",
			Handler:    _AlliDB_PutEntity_Handler,
		},
		{
			MethodName: "BatchPutEntities",
			Handler:    _AlliDB_BatchPutEntities_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _AlliDB_Query_Handler,
		},
		{
			MethodName: "RangeScan",
			Handler:    _AlliDB_RangeScan_Handler,
		},
		{
			MethodName: "ReplicaRead",
			Handler:    _AlliDB_ReplicaRead_Handler,
		},
		{
			MethodName: "ReplicaWrite",
			Handler:    _AlliDB_ReplicaWrite_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AlliDB_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/allidb.proto",
}
